// import img01_pr from "../../images/img01_pr.jpg";
// import img02_pr from "../../images/img02_pr.jpg";
// import img03_pr from "../../images/img03_pr.jpg";
// import img04_pr from "../../images/img04_pr.jpg";
// import img05_pr from "../../images/img05_pr.jpg";
// import img06_pr from "../../images/img06_pr.jpg";
// import img07_pr from "../../images/img07_pr.jpeg";
// import img08_pr from "../../images/img08_pr.jpg";
// import img09_pr from "../../images/img09_pr.jpg";
// import img10_pr from "../../images/img10_pr.jpg";
// import img11_pr from "../../images/img11_pr.jpg";
// import img12_pr from "../../images/img12_pr.jpeg";
// import img13_pr from "../../images/img13_pr.jpg";
// import img14_pr from "../../images/img14_pr.jpg";
// import img15_pr from "../../images/img15_pr.jpeg";
// import img16_pr from "../../images/img16_pr.jpeg";
// import img17_pr from "../../images/img17_pr.jpg";
// import img18_pr from "../../images/img18_pr.webp";
// import img19_pr from "../../images/img19_pr.jpg";
// import img20_pr from "../../images/img20_pr.jpeg";
// import img21_pr from "../../images/img21_pr.jpeg";
// import img22_pr from "../../images/img22_pr.jpg";
// import img23_pr from "../../images/img23_pr.jpg";
// import img24_pr from "../../images/img24_pr.jpg";


// const prodData = [

//     {
//         id: 1,
//         category: "Books",
//         condition: "Like New",
//         acc_rating: 25,
//         prod_name: "Schaum series data structures",
//         imgUrl: img01_pr,
//         altImages: [
//             img01_pr , img02_pr , img03_pr , img04_pr
//         ],
        
//         delivery: "20 June",
//         price: 399,
//         origPrice: 600,
//         dimensions: "20*15 cm",
//         material: "paperback cover", 
//         rentavailibility: "Available for rent",
//         duration: "6 months",
//         rentprice: 100,
//         description: "Comprehensive guide on data structures with numerous examples and exercises.",
//     },
//     {
//         id: 2,
//         category: "Courses",
//         condition: "New",
//         acc_rating: 120,
//         prod_name: "DSA in Python- Coding Ninjas",
//         imgUrl: img02_pr,
//         delivery: "by 26 June",
//         price: 1999,
//         origPrice: 2500,
//         dimensions: "N/A",
//         material: "N/A", 
//         rentavailibility: "Not available for rent",
//         duration: "",
//         rentprice: "",
//         description: "In-depth course on Data Structures and Algorithms in Python by Coding Ninjas.",
//     },
//     {
//         id: 3,
//         category: "Electronics",
//         condition: "Used - Good",
//         acc_rating: 75,
//         prod_name: "Ecolink Lamp By Philips",
//         imgUrl: img03_pr,
//         delivery: "by 30 June",
//         price: 1299,
//         origPrice: 1500,
//         dimensions: "30*10 cm",
//         material: "plastic and metal", 
//         rentavailibility: "Available for rent",
//         duration: "6 months",
//         rentprice: 100,
//         description: "Energy-efficient and durable lamp from Philips, ideal for study and work.",
//     },
//     {
//         id: 4,
//         category: "Utensils",
//         condition: "Used - Acceptable",
//         acc_rating: 50,
//         prod_name: "Utopia Non Stick Frying Pan",
//         imgUrl: img04_pr,
//         delivery: "by 22 June",
//         price: 499,
//         origPrice: 800,
//         dimensions: "25*5 cm",
//         material: "non-stick coated metal", 
//         rentavailibility: "Not available for rent",
//         duration: "",
//         rentprice: "",
//         description: "High-quality non-stick frying pan perfect for all your cooking needs.",
//     },
//     {
//         id: 5,
//         category: "Furniture",
//         condition: "Refurbished",
//         acc_rating: 10,
//         prod_name: "High Back Office Chair",
//         imgUrl: img05_pr,
//         delivery: "by 28 June",
//         price: 600,
//         origPrice: 1100,
//         dimensions: "50*50*100 cm",
//         material: "fabric and metal", 
//         rentavailibility: "Available for rent",
//         duration: "1 year",
//         rentprice: 200,
//         description: "Ergonomic high back office chair with adjustable height and lumbar support.",
//     },
//     {
//         id: 6,
//         category: "Others",
//         condition: "New",
//         acc_rating: 5,
//         prod_name: "Metal Flower Pot Amazon",
//         imgUrl: img06_pr,
//         delivery: "5 July",
//         price: 500,
//         origPrice: 900,
//         dimensions: "15*15 cm",
//         material: "galvanized metal", 
//         rentavailibility: "Not available for rent",
//         duration: "",
//         rentprice: "",
//         description: "Stylish metal flower pot, perfect for indoor and outdoor plants.",
//     },
//     {
//         id: 7,
//         category: "Books",
//         condition: "New",
//         acc_rating: 50,
//         prod_name: "Basic Electrical Engineering",
//         imgUrl: img07_pr,
//         delivery: "5 July",
//         price: 500,
//         origPrice: 700,
//         dateOfProd: "2023-03-18",
//         dimensions: "22*15 cm",
//         material: "paperback cover", 
//         rentavailibility: "Available for rent",
//         duration: "6 months",
//         rentprice: 150,
//         description: "Comprehensive guide on basic electrical engineering concepts.",
//     },
//     {
//         id: 8,
//         category: "Books",
//         condition: "New",
//         acc_rating: 60,
//         prod_name: "Fundamental Mathematics",
//         imgUrl: img08_pr,
//         delivery: "10 July",
//         price: 550,
//         origPrice: 750,
//         dateOfProd: "2023-01-10",
//         dimensions: "23*16 cm",
//         material: "hardcover", 
//         rentavailibility: "Available for rent",
//         duration: "1 year",
//         rentprice: 250,
//         description: "Fundamental concepts of engineering mathematics with solved examples.",
//     },
//     {
//         id: 9,
//         category: "Books",
//         condition: "New",
//         acc_rating: 70,
//         prod_name: "Digital Electronics-All in one",
//         imgUrl: img09_pr,
//         delivery: "15 July",
//         price: 600,
//         origPrice: 800,
//         dateOfProd: "2022-12-05",
//         dimensions: "24*17 cm",
//         material: "paperback cover", 
//         rentavailibility: "Available for rent",
//         duration: "6 months",
//         rentprice: 200,
//         description: "All-inclusive guide on digital electronics, covering basics to advanced topics.",
//     },
//     {
//         id: 10,
//         category: "Books",
//         condition: "New",
//         acc_rating: 40,
//         prod_name: "Basic Mechanical Engineering",
//         imgUrl: img10_pr,
//         delivery: "20 July",
//         price: 520,
//         origPrice: 720,
//         dateOfProd: "2023-02-15",
//         dimensions: "25*18 cm",
//         material: "paperback cover", 
//         rentavailibility: "Available for rent",
//         duration: "1 year",
//         rentprice: 180,
//         description: "Introduction to basic mechanical engineering concepts with practical applications.",
//     },
//     {
//         id: 11,
//         category: "Books",
//         condition: "New",
//         acc_rating: 80,
//         prod_name: "Artificial Intelligence for B.Tech",
//         imgUrl: img11_pr,
//         delivery: "25 July",
//         price: 650,
//         origPrice: 850,
//         dateOfProd: "2023-04-20",
//         dimensions: "26*19 cm",
//         material: "hardcover", 
//         rentavailibility: "Available for rent",
//         duration: "1 year",
//         rentprice: 300,
//         description: "Comprehensive textbook on artificial intelligence for B.Tech students.",
//     },
//     {
//         id: 12,
//         category: "Electronics",
//         condition: "New",
//         acc_rating: 30,
//         prod_name: "Philips 2100W Electric Induction",
//         imgUrl: img12_pr,
//         delivery: "30 July",
//         price: 1500,
//         origPrice: 2000,
//         dateOfProd: "2023-03-18",
//         dimensions: "30*30 cm",
//         material: "glass and plastic", 
//         rentavailibility: "Not available for rent",
//         duration: "",
//         rentprice: "",
//         description: "High-efficiency 2100W electric induction cooktop from Philips.",
//     },
//     {
//         id: 13,
//         category: "Electronics",
//         condition: "New",
//         acc_rating: 20,
//         prod_name: "Bajaj 1.5L Electric Kettle",
//         imgUrl: img13_pr,
//         delivery: "5 August",
//         price: 800,
//         origPrice: 1000,
//         dateOfProd: "2023-01-25",
//         dimensions: "20*20 cm",
//         material: "stainless steel", 
//         rentavailibility: "Available for rent",
//         duration: "6 months",
//         rentprice: 300,
//         description: "Durable and quick heating 1.5L electric kettle from Bajaj.",
//     },
//     {
//         id: 14,
//         category: "Electronics",
//         condition: "New",
//         acc_rating: 35,
//         prod_name: "Philips White Electric Hand Blender",
//         imgUrl: img14_pr,
//         delivery: "10 August",
//         price: 1200,
//         origPrice: 1500,
//         dateOfProd: "2023-02-10",
//         dimensions: "10*10 cm",
//         material: "plastic", 
//         rentavailibility: "Not available for rent",
//         duration: "",
//         rentprice: "",
//         description: "Compact and powerful electric hand blender from Philips.",
//     },
//     {
//         id: 15,
//         category: "Electronics",
//         condition: "New",
//         acc_rating: 45,
//         prod_name: "Flat Iron Hair Straightener",
//         imgUrl: img15_pr,
//         delivery: "15 August",
//         price: 1000,
//         origPrice: 1300,
//         dateOfProd: "2023-03-01",
//         dimensions: "15*5 cm",
//         material: "ceramic", 
//         rentavailibility: "Not available for rent",
//         duration: "",
//         rentprice: "",
//         description: "Professional-grade flat iron hair straightener for smooth and shiny hair.",
//     },
//     {
//         id: 16,
//         category: "Others",
//         condition: "New",
//         acc_rating: 5,
//         prod_name: "Wooden Desk Organizer",
//         imgUrl: img16_pr,
//         delivery: "5 July",
//         price: 500,
//         origPrice: 700,
//         dateOfProd: "2023-03-18",
//         dimensions: "20*10 cm",
//         material: "wood", 
//         rentavailibility: "Not available for rent",
//         duration: "",
//         rentprice: "",
//         description: "Organize your desk with this stylish wooden desk organizer.",
//     },
//     {
//         id: 17,
//         category: "Others",
//         condition: "Like New",
//         acc_rating: 4,
//         prod_name: "Boat Wireless Headphones",
//         imgUrl: img17_pr,
//         delivery: "10 July",
//         price: 1500,
//         origPrice: 2000,
//         dateOfProd: "2023-02-10",
//         dimensions: "10*10 cm",
//         material: "plastic", 
//         rentavailibility: "Not available for rent",
//         duration: "",
//         rentprice: "",
//         description: "Experience wireless freedom with Boat's high-quality headphones.",
//     },
//     {
//         id: 18,
//         category: "Furniture",
//         condition: "Used - Good",
//         acc_rating: 3,
//         prod_name: "Small Size Foldable Study Table",
//         imgUrl: img18_pr,
//         delivery: "15 July",
//         price: 800,
//         origPrice: 1000,
//         dateOfProd: "2023-01-25",
//         dimensions: "40*30 cm",
//         material: "wood and metal", 
//         rentavailibility: "Available for rent",
//         duration: "1 year",
//         rentprice: 300,
//         description: "Compact and foldable study table, perfect for small spaces.",
//     },
//     {
//         id: 19,
//         category: "Furniture",
//         condition: "New",
//         acc_rating: 5,
//         prod_name: "Wooden Study Table for Bed",
//         imgUrl: img19_pr,
//         delivery: "20 July",
//         price: 1200,
//         origPrice: 1500,
//         dateOfProd: "2023-02-15",
//         dimensions: "50*30 cm",
//         material: "wood", 
//         rentavailibility: "Available for rent",
//         duration: "1 year",
//         rentprice: 400,
//         description: "Convenient study table designed for use on the bed.",
//     },
//     {
//         id: 20,
//         category: "Furniture",
//         condition: "Like New",
//         acc_rating: 4,
//         prod_name: "Teak Finish Back Rest Chair",
//         imgUrl: img20_pr,
//         delivery: "25 July",
//         price: 2000,
//         origPrice: 2500,
//         dateOfProd: "2023-04-20",
//         dimensions: "60*60 cm",
//         material: "teak wood", 
//         rentavailibility: "Available for rent",
//         duration: "3 months",
//         rentprice: 200,
//         description: "Comfortable chair with a teak finish, perfect for home offices.",
//     },
//     {
//         id: 21,
//         category: "Furniture",
//         condition: "Used - Like New",
//         acc_rating: 4,
//         prod_name: "Mini Cupboard by TeakLab",
//         imgUrl: img21_pr,
//         delivery: "30 July",
//         price: 3000,
//         origPrice: 3500,
//         dateOfProd: "2023-03-18",
//         dimensions: "40*60 cm",
//         material: "teak wood", 
//         rentavailibility: "Available for rent",
//         duration: "6 months",
//         rentprice: 500,
//         description: "Stylish and compact mini cupboard from TeakLab.",
//     },
//     {
//         id: 22,
//         category: "Electronics",
//         condition: "New",
//         acc_rating: 5,
//         prod_name: "1.2L Mini Rice Cooker",
//         imgUrl: img22_pr,
//         delivery: "5 August",
//         price: 700,
//         origPrice: 900,
//         dateOfProd: "2023-01-10",
//         dimensions: "20*20 cm",
//         material: "stainless steel", 
//         rentavailibility: "Available for rent",
//         description: "Compact and efficient mini rice cooker for small servings.",
//     },
//     {
//         id: 23,
//         category: "Utensils",
//         condition: "Used - Good",
//         acc_rating: 3,
//         prod_name: "500ml Thermos Flask Dura Steel",
//         imgUrl: img23_pr,
//         delivery: "10 August",
//         price: 500,
//         origPrice: 700,
//         dateOfProd: "2022-11-25",
//         dimensions: "25*10 cm",
//         material: "stainless steel", 
//         rentavailibility: "Not available for rent",
//         duration: "",
//         rentprice: "",
//         description: "Durable 500ml thermos flask for keeping drinks hot or cold.",
//     },
//     {
//         id: 24,
//         category: "Utensils",
//         condition: "New",
//         acc_rating: 5,
//         prod_name: "4L Ashafa Thermos",
//         imgUrl: img24_pr,
//         delivery: "15 August",
//         price: 800,
//         origPrice: 1000,
//         dateOfProd: "2023-03-01",
//         dimensions: "30*20 cm",
//         material: "stainless steel", 
//         rentavailibility: "Not available for rent",
//         duration: "",
//         rentprice: "",
//         description: "Large 4L thermos, perfect for keeping beverages hot or cold for hours.",
//     },
// ];

// export default prodData;
