import img07_pr from "../../images/img07_pr.jpeg";
import img08_pr from "../../images/img08_pr.jpg";
import img09_pr from "../../images/img09_pr.jpg";
import img10_pr from "../../images/img10_pr.jpg";
import img11_pr from "../../images/img11_pr.jpg";
import img12_pr from "../../images/img12_pr.jpeg";
import img13_pr from "../../images/img13_pr.jpg";
import img14_pr from "../../images/img14_pr.jpg";
import img15_pr from "../../images/img15_pr.jpeg";

const prodData = [
    {
        id: 7,
        category: "Books",
        condition: "New",
        acc_rating: 50,
        prod_name: "Basic Electrical Engineering",
        imgUrl: img07_pr,
        delivery: "5 July",
        price: 500,
        origPrice: 700,
        dateOfProd: "2023-03-18",
        dimensions: "22*15 cm",
        material: "paperback cover", 
        rentavailibility: "Available for rent",
        description: "Comprehensive guide on basic electrical engineering concepts.",
    },
    {
        id: 8,
        category: "Books",
        condition: "New",
        acc_rating: 60,
        prod_name: "Fundamental Engineering Mathematics",
        imgUrl: img08_pr,
        delivery: "10 July",
        price: 550,
        origPrice: 750,
        dateOfProd: "2023-01-10",
        dimensions: "23*16 cm",
        material: "hardcover", 
        rentavailibility: "Available for rent",
        description: "Fundamental concepts of engineering mathematics with solved examples.",
    },
    {
        id: 9,
        category: "Books",
        condition: "New",
        acc_rating: 70,
        prod_name: "Digital Electronics-All in one",
        imgUrl: img09_pr,
        delivery: "15 July",
        price: 600,
        origPrice: 800,
        dateOfProd: "2022-12-05",
        dimensions: "24*17 cm",
        material: "paperback cover", 
        rentavailibility: "Available for rent",
        description: "All-inclusive guide on digital electronics, covering basics to advanced topics.",
    },
    {
        id: 10,
        category: "Books",
        condition: "New",
        acc_rating: 40,
        prod_name: "Basic Mechanical Engineering",
        imgUrl: img10_pr,
        delivery: "20 July",
        price: 520,
        origPrice: 720,
        dateOfProd: "2023-02-15",
        dimensions: "25*18 cm",
        material: "paperback cover", 
        rentavailibility: "Available for rent",
        description: "Introduction to basic mechanical engineering concepts with practical applications.",
    },
    {
        id: 11,
        category: "Books",
        condition: "New",
        acc_rating: 80,
        prod_name: "Artificial Intelligence for B.Tech",
        imgUrl: img11_pr,
        delivery: "25 July",
        price: 650,
        origPrice: 850,
        dateOfProd: "2023-04-20",
        dimensions: "26*19 cm",
        material: "hardcover", 
        rentavailibility: "Available for rent",
        description: "Comprehensive textbook on artificial intelligence for B.Tech students.",
    },
    {
        id: 12,
        category: "Electronics",
        condition: "New",
        acc_rating: 30,
        prod_name: "Philips 2100W Electric Induction",
        imgUrl: img12_pr,
        delivery: "30 July",
        price: 1500,
        origPrice: 2000,
        dateOfProd: "2023-03-18",
        dimensions: "30*30 cm",
        material: "glass and plastic", 
        rentavailibility: "Available for rent",
        description: "High-efficiency 2100W electric induction cooktop from Philips.",
    },
    {
        id: 13,
        category: "Electronics",
        condition: "New",
        acc_rating: 20,
        prod_name: "Bajaj 1.5L Electric Kettle",
        imgUrl: img13_pr,
        delivery: "5 August",
        price: 800,
        origPrice: 1000,
        dateOfProd: "2023-01-25",
        dimensions: "20*20 cm",
        material: "stainless steel", 
        rentavailibility: "Available for rent",
        description: "Durable and quick heating 1.5L electric kettle from Bajaj.",
    },
    {
        id: 14,
        category: "Electronics",
        condition: "New",
        acc_rating: 35,
        prod_name: "Philips White Electric Hand Blender",
        imgUrl: img14_pr,
        delivery: "10 August",
        price: 1200,
        origPrice: 1500,
        dateOfProd: "2023-02-10",
        dimensions: "10*10 cm",
        material: "plastic", 
        rentavailibility: "Available for rent",
        description: "Compact and powerful electric hand blender from Philips.",
    },
    {
        id: 15,
        category: "Electronics",
        condition: "New",
        acc_rating: 45,
        prod_name: "Flat Iron Hair Straightener",
        imgUrl: img15_pr,
        delivery: "15 August",
        price: 1000,
        origPrice: 1300,
        dateOfProd: "2023-03-01",
        dimensions: "15*5 cm",
        material: "ceramic", 
        rentavailibility: "Available for rent",
        description: "Professional-grade flat iron hair straightener for smooth and shiny hair.",
    },
];

export default prodData;
